name: alalaq_shop
description: "متجر الألق للتسويق الإلكتروني"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  flutter_svg: any
  http: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: any
  flutter_native_splash: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700

# ✅ إعداد أيقونة التطبيق (باستخدام PNG شفافة)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/iconApp.png"
  adaptive_icon_background: "#b1e2f3"
  adaptive_icon_foreground: "assets/images/iconApp.png"
  remove_alpha_ios: true

# ✅ إعداد Splash Screen (صورة PNG وسطية بدون تمدد)
flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#b1e2f3"  # لون خلفية شاشة البداية

  image: assets/images/iconApp.png
  android_gravity: center
  ios_content_mode: scaleAspectFit

  fullscreen: true
